### ISSUE TITLE
JOSS submission/First release (Meta Issue)

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/Palaeoanalytics#73]
In order to submit the package to JOSS we need to improve the documentation of the code:

Things to do:

- [x] Make sure all functions have accurate [docstring comments](https://www.python.org/dev/peps/pep-0257/) 
- [x] Improve test code coverage
- [x] Improve README with a more detailed description of the project
- [x] Output images
- [x] Select a set of images to have an open proof of concept (do we need to ask for permisions for this? @JasonGellis)
- [ ] Publish the PA_DB.csv dataset in a open data repository (https://zenodo.org/, or https://msuintrodhfall2020.hcommons.org/ ) 
- [ ] Run a Readthedocs page https://readthedocs.org/
- [x] Adding contributing guidelines and licence
- [x] Opening the code
